---
abstract: 'Use Test::* tests outside of a TAP context'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Carp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101590'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Wrapper
requires:
  Moose: 0
  Moose::Exporter: 0
  Test::Builder: 0
  overload: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Wrapper
  homepage: http://search.cpan.org/dist/Test-Wrapper/
  repository: git://github.com/yanick/test-wrapper.git
version: 0.1.0
